### PR TITLE
Test/issue92 automated

### PR DESCRIPTION
**Pull request by B1TC0R3**
Hello @gungula, this pull request is mainly relevant for you.
I have added a brief documentation of the different testing methods I employed for the project, and would like you to review and potentially build upon it.

Thanks :)

### CODE REVIEW

**Comment by janschaible** [comment]
@B1TC0R3 great work :) I belive that these changes belong in read the docs as well ?:)
to accomplish this, you would need to converte your file to a .rst file and put it in the docs/source folder :)

**Comment by B1TC0R3** [comment]
Let me take care of that.

**Comment by B1TC0R3** [comment]
@gungula @janschaible I have created a `.rst` file, I would replace `025_tests.rst` with it. Is this OK, or do I need to keep something else in mind while doing this?

**Comment by gungula** [comment]
> @gungula @janschaible I have created a `.rst` file, I would replace `025_tests.rst` with it. Is this OK, or do I need to keep something else in mind while doing this?

It is relevant to name the file exactly like the existing one and putting it in the same place. I copied the content from your .rst and made some very small formatting fittings - you could delete the testing-oxide.rst.
Looks great, thank you!

**Review by gungula — CHANGES_REQUESTED** [review]
Why are the index.rst files from 033_class_diagrams_generated/windowmanager and 033_class_diagrams_generated/extensions/oxide-bar deleted? They are relevant for building the diagrams in read the docs. Do you have any clue @B1TC0R3  ?

**Comment by B1TC0R3** [comment]
Yea, I deleted those because I thought they were automatically generated and caused merge issues.
Let me restore them really quickly.

**Review by gungula — APPROVED** [review]

**Comment by gungula** [comment]
> Yea, I deleted those because I thought they were automatically generated and caused merge issues. Let me restore them really quickly.

fyi: The `index.rst`-files are the "landingpages" of the (sub-)sections where the table of contents are entered and, in some cases, already some diagrams or other texts. Automatically generated are only the classdiagrams and if they have changes they are automatically fitted in the readthedocs, but only as far as @janschaible made according templates :)

> 
> [EDIT] Files should be restored now.

Perfect, ready to merge now.

**Pull request merged**
