### PR TITLE
feature/ISSUE203-extensions-class-diagrams

### PR DESCRIPTION
**Pull request by janschaible**
@gungula soll ich probieren, die klassendiagramme auch in die read the docs rein zu generieren ?:) müsste mir halt was einfallen lassen mit der breite, denke aber das kann ich aus der anzahl der pixel berechnen ?:)

Und @gungula bist du gerade noch dabei das lasten und pflichtenheft um zu ziehen ?:) Falls ja, dürfen wir nicht vergessen das md dokument zu löschen, dass wir nicht zwei verschiedene stellen haben, an denen das rumliegt :)

### CODE REVIEW

**Comment by gungula** [comment]
> @gungula soll ich probieren, die klassendiagramme auch in die read the docs rein zu generieren ?:) müsste mir halt was einfallen lassen mit der breite, denke aber das kann ich aus der anzahl der pixel berechnen ?:)
> 
> Und @gungula bist du gerade noch dabei das lasten und pflichtenheft um zu ziehen ?:) Falls ja, dürfen wir nicht vergessen das md dokument zu löschen, dass wir nicht zwei verschiedene stellen haben, an denen das rumliegt :)

Yes, the moving is still in progress but thank you for the hint :)

I'll take care about implementing them on readthedocs tomorrow :) 

Anyways I guess I will browse through all the diagrams shortly before our presentation and the submission to make sure all the diagrams on readthedocs are connected correctly.

**Review by gungula — APPROVED** [review]
Looks like kinda much work - thank you, that's great! :)

**Comment by janschaible** [comment]
I will leave this branch unmerged than and take a look if we could generate the read the doc links :)

> At this point I would be grateful if you could help me

No not really :) But thanks for always writing so nicely :)

**Comment by janschaible** [comment]
@gungula would you please take a look at the generated diagrams again ?:)
I'd really like to know what could be done better from our rst expert ;)

**Comment by gungula** [comment]
> @gungula would you please take a look at the generated diagrams again ?:) I'd really like to know what could be done better from our rst expert ;)

Looks like we are two of them now ;) 

I have three small suggestions: 
- I'd like to have a small hint on the top of the pages like e. g. on "flowcharts", too. It should say something like "If the diagrams are not shown big enough to read, please click on them.". Not essential but really fancy ;) 

`.. hint::
    If the diagrams are not shown big enough to read, please click on them.
`

- Is it possible to name the diagrams a little bit more clearly or writing a small comment below the diagram, not only using its name? For example xcb_visualtype. Someone who doesn't know the project quite as good as we would maybe not know what is meant here. Same with the "mod"s. For this it guess it would be an option to write some explanation on the class diagramm - mainpage. 
I am not sure if the above mentioned naming or commenting is possible because of being generated automatically - please let me know if i am wrong :)

- The size of the diagrams: Some of them like e.g. workspace/parse_error are shown really big while others (e.g. workspace/mod) are kind of small. Most of them have a good size i guess - are the widths generated automatically, too or do we set them manually like in the other diagrams? At this point i think the hint will be useful, too :)

What do you think?

**Comment by janschaible** [comment]
@gungula 
I added the hints, adjusted the width, i used the px parameter :/ But this is a max width, maybe you could take a look if this behaviour is ok too ?:)
I will take a look at the naming later :)

**Comment by janschaible** [comment]
@gungula did change the naming, hope this naming is acceptable, otherwise it will become complicated :)
What else do we have to do before we can write mr kergreis to take a look at our project again ?:)

**Review by FelixSchladt — APPROVED** [review]

**Pull request merged**
